# Utilisation d'une image légère avec Python 3.9
FROM python:3.9-alpine

# Définition du dossier de travail dans le conteneur
WORKDIR /app

# Port sur lequel le service écoute à l'intérieur du conteneur
EXPOSE 8000

# Point d'entrée : Le script qui lance le service
ENTRYPOINT ["./script.sh"]
